### ISSUE TITLE
\bar doesn't work

### ISSUE THREAD

**Issue by ForNeVeR** [ForNeVeR/xaml-math#288]
From a command like `\bar{X}`, I expect to do something like this: 
![image](https://user-images.githubusercontent.com/92793/104848706-d1dde700-5918-11eb-8c0f-62ba250a4055.png)

But in WPF-Math, it does nothing:
![image](https://user-images.githubusercontent.com/92793/104848790-f76af080-5918-11eb-8d42-a29f2869d7bc.png)

**Comment by justnope** [comment]
I've checked it and it does work. Even in your posted image does it draw a bar. Enlarge it and you'll see a faint bar drawn above.

I think this might be a pixel alignment issue. TTF files support a script language that can be executed during the rendering of that font. If I'm not mistaken one of its uses is to avoid these "subpixel" errors and aligns the things (like a horizontal bar) to a pixel.

Let me know if you want me to look further into it.

If we're lucky we only need to update the ttf files.

**Comment by PapisKang** [comment]
Hi @ForNeVeR 
I just tested it and it seems fixed isnt it ? 
![image](https://github.com/ForNeVeR/xaml-math/assets/47726365/614f9833-5762-41ed-971d-e6bc548f6ca4)

**Comment by ForNeVeR** [comment]
I have just discovered that it kinda worked on the old version (commit `c60038eda6d61607bb7b141c2537fccd3c3c600d`, the last one as of 2024-01-17) as well: the bar was just barely visible (seemingly one-pixel high?)

![image](https://github.com/ForNeVeR/xaml-math/assets/92793/4e7da2dc-7c6b-4ba7-b79b-c6c6f10fd777)

On the modern versions, it works fine indeed.
