### ISSUE TITLE
Review .NET version support

### ISSUE THREAD

**Issue by ForNeVeR** [ForNeVeR/xaml-math#335]
Last year, official support for.NET Framework 4.5.2 finally ended. Same for .NET Core 3.1.

We should review the currently supported .NET versions and leave only the ones that are still supported (4.6.2 is the oldest supported Framework version at the current moment, and .NET 6 is the oldest supported version of the modern runtime).

We could try migrating to .NET Standard instead of .NET Framework, but I'm not sure it's possible to target WPF projects to .NET Standard.

**Comment by ygra** [comment]
> I'm not sure it's possible to target WPF projects to .NET Standard

You cannot, no. WPF is only supported in the Windows-specific TFMs that correspond to a normal .NET TFM (net6.0-windows, etc.). .NET Standard (even though it's somewhat dead by now) is strictly cross-platform. You could use it for Avalonia, though.
